version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/contacts-book-app
    restart: always
    depends_on:
      - php

  php:
    build:
      args:
        user: www
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./backend/:/var/www/contacts-book-app/backend
    tty: true
    restart: always

  vue:
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - "8080:80"
    volumes:
      - ./frontend/:/var/www/contacts-book-app/frontend
      - /var/www/contacts-book-app/frontend/node_modules